sudo: false
language: php
php:
  - 7.0
services:
  - mysql
matrix:
  allow_failures:
    - php: hhvm
before_script:
#  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_ AUTH
  - mysql -uroot -e 'create database symfony;'
  - composer install --no-interaction --prefer-dist
script:
  - bin/phpcs -p --standard=PSR2 --extensions=php ./src
