<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Activity;
use \Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    /**
     * @return string[]
     */
    public function getActivityList()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a.name')->from('AppBundle:Activity', 'a');
        $activities = $qb->getQuery()->execute();

        foreach ($activities as $key => $activity) {
            $activities[$key] = $activity['name'];
        }

        return $activities;
    }

    /**
     * @return Activity[]
     */
    public function getAllActivities()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a')->from('AppBundle:Activity', 'a');

        return $qb->getQuery()->execute();
    }
}
