<?php

namespace AppBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    /**
     * @return string[]
     */
    public function getActivityList()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a.name')->from('AppBundle:Activity', 'a');
        $activities = $qb->getQuery()->execute();

        foreach ($activities as $key => $activity) {
            $activities[$key] = $activity['name'];
        }

        return $activities;
    }
}
