<?php

namespace AppBundle\Repository;

use AppBundle\Entity\OfferImage;
use \Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferImageRepository extends EntityRepository
{
    /**
     * @return OfferImage[]
     */
    public function getImages()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a')->from('AppBundle:OfferImage', 'a');
        return $qb->getQuery()->execute();
    }
}
