app:
    resource: @AppBundle/Resources/config/routing.yml
    type: yaml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile_edit:
    path: /profile
    defaults: { _controller: FOSUserBundle:Profile:edit }

fos_user_registration_register:
    path: /register
    defaults: { _controller: FOSUserBundle:Registration:register }

fos_user_registration_confirmed:
    path: /confirmed
    defaults: { _controller: FOSUserBundle:Registration:confirmed }