app.index:
  path:     /
  defaults: { _controller: AppBundle:Home:index }

app.search:
  path:     /search
  defaults: { _controller: AppBundle:Home:search }

app.coaches:
  path: /coaches
  defaults: { _controller: AppBundle:Home:coaches }

app.offerDetails:
  path: /offer/{id}
  defaults: { _controller: AppBundle:Home:offerDetails }

app.registeredOffers:
  path: /offers/
  defaults: { _controller: AppBundle:Home:offers }

app.offerDelete:
  path: /offers/delete/{id}
  defaults: { _controller: AppBundle:Home:offerDelete }

app.offerImport:
  path: /offers/import
  defaults: { _controller: AppBundle:Home:offerImport }

app.activityCreate:
  path: /activity
  defaults: { _controller: AppBundle:Home:activityCreate }

app.activityEdit:
  path: /activityEdit/{id}
  defaults: { _controller: AppBundle:Home:activityEdit }