app.index:
  path:     /
  defaults: { _controller: AppBundle:Home:index }

app.search:
  path:     /search
  defaults: { _controller: AppBundle:Home:search }

app.login:
  path: /login
  defaults: { _controller: AppBundle:Home:login}

app.coaches:
  path: /coaches
  defaults: { _controller: AppBundle:Home:coaches}

app.offerDetails:
  path: /offer/{id}
  defaults: { _controller: AppBundle:Home:offerDetails}
