AppBundle\Entity\User:
    properties:
        name:
            - NotBlank:
                message: "Prašome įvesti savo vardą ir pavardę"
                groups: [ "CustomProfile", "CustomRegistration" ]
        phone:
            - NotBlank:
                message: "Prašome įvesti savo telefono numerį"
                groups: [ "CustomProfile", "CustomRegistration" ]
            - AppBundle\Validator\Constraints\PhoneNumber:
                message: "Telefono numeris neteisingas"
                groups: [ "CustomProfile", "CustomRegistration" ]

AppBundle\Entity\Comment:
    properties:
        name:
            - NotBlank:
                message: "Prašome įvesti savo vardą"
            - Length:
                min: 2
                minMessage: "Jūsų vardas per trumpas"
                max: 50
                maxMessage: "Jūsų vardas per ilgas"
        email:
            - NotBlank:
                message: "Prašome įvesti savo el. paštą"
            - Email:
                message: "Prašome įvesti tikrą el. paštą"
        title:
            - NotBlank:
                message: "Prašome įvesti temą"
            - Length:
                min: 2
                minMessage: "Jūsų tema per trumpa"
                max: 100
                maxMessage: "Jūsų tema per ilga"
        body:
            - NotBlank:
                message: "Prašome įvesti atsiliepimą"
            - Length:
                min: 5
                minMessage: "Prašome parašyti išsamiau"
                max: 1000
                maxMessage: "Jūsų žinutė per ilga, daugiausiai 1000 simbolių"
        rate:
            - NotBlank:
                message: "Prašome palikti įvertinimą"

FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: email
             errorPath: email
             message: fos_user.email.already_used
             groups: [ "CustomRegistration" ]

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "CustomRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "CustomRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "CustomRegistration" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "CustomRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 6
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "CustomRegistration", "CustomProfile", "ResetPassword", "ChangePassword"]
